// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SetDecadeController from "./set_decade_controller"
application.register("set-decade", SetDecadeController)

import SetGenreController from "./set_genre_controller"
application.register("set-genre", SetGenreController)

import VotingController from "./voting_controller"
application.register("voting", VotingController)
