// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import EventSubscriptionController from "./event_subscription_controller"
application.register("event-subscription", EventSubscriptionController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SetDecadeController from "./set_decade_controller"
application.register("set-decade", SetDecadeController)

import SetGenreController from "./set_genre_controller"
application.register("set-genre", SetGenreController)

import SetUsersController from "./set_users_controller"
application.register("set-users", SetUsersController)

import VotingController from "./voting_controller"
application.register("voting", VotingController)

import ReadMore from 'stimulus-read-more'
Stimulus.register('read-more', ReadMore)
