meta_name: "movie2night"
meta_title: "movie2night - Don't waste your time choosing a movie"
meta_description: "Quickly and easily find a movie for your next movie night"
meta_image: "app/assets/images/cover.png"
